### ISSUE TITLE
鱼啊 高德地图有点问题lie

### ISSUE THREAD

**Issue by serydoo** [ddgksf2013/ddgksf2013#34]
16号最后 他的数据就无法同步了 ，搜索也会出现问题，我用的应该是默认配置 ，有人遇到同样问题吗

**Comment by wh2724** [comment]
同遇到 搜索有问题

**Comment by ddgksf2013** [comment]
把blackmatrix7的去广告重写删掉

**Comment by serydoo** [comment]
我重置了圈x，重新导入你的配置及好了，之前脑袋一热，挂载了耳东成的那个经纬度解锁国行功能的配置，乱七八糟的，删除都删除不干净

**Comment by hbprotoss** [comment]
> 把blackmatrix7的去广告重写删掉

没看明白，好像最新规则里没这个，还是不行
