### ISSUE TITLE
Bilibili动态页去广告失效

### ISSUE THREAD

**Issue by Mon5ter777** [ddgksf2013/ddgksf2013#36]
无论使用白色bilibili还是粉色bilibili，均会出现   你可能喜欢的up主   
软件使用qx在仅使用墨鱼规则的bilibili相关重写的情况下依旧存在   你可能喜欢的up主
清理软件缓存或者重新安装软件均以尝试，且无效。

**Comment by jjb727** [comment]
腾讯手机管家 开屏广告失效
