### ISSUE TITLE
Mac使用圈x小白规则2.0百度网盘无法登入

### ISSUE THREAD

**Issue by dqzboy** [ddgksf2013/ddgksf2013#53]
在Mac上使用墨鱼自用QX配置，百度网盘无法登入，不管是扫码还是账号都无法登入，扫码成功直接显示登入失败，重新登入。关闭圈x或者模式改为全部直连可以正常登入
<img width="912" alt="image" src="https://github.com/ddgksf2013/ddgksf2013/assets/42825450/f42c3340-b7f0-41be-9969-777a49718201">

**Comment by LouisLoong** [comment]
我也有这问题
