### ISSUE TITLE
challenges.cloudflare.com无法通过检测

### ISSUE THREAD

**Issue by xiaohundun** [ddgksf2013/ddgksf2013#61]
openai 里的这个规则强制使用美国节点，但是这个域名的检测无法通过，有遇到相同情况的么

**Comment by LINXIANN** [comment]
> openai 里的这个规则强制使用美国节点，但是这个域名的检测无法通过，有遇到相同情况的么
换个机场试试看，我这浏览器里可以正常用，app就不行了
