### ISSUE TITLE
QX有办法升级懒人规则，而不用重新生成证书，再重新导入节点，的操作方法么？

### ISSUE THREAD

**Issue by star2k** [ddgksf2013/ddgksf2013#7]
QX有办法升级懒人规则，而不用重新生成证书，再重新导入节点，的操作方法么？

**Comment by ddgksf2013** [comment]
# 🟢 passphrase和p12代为证书&主机名部分, 更新配置前可把旧的配置中passphrase和p12代码拷贝下来, 导入新的配置文件把内容粘贴在对应位置就不用重装证书
