### ISSUE TITLE
bilibili播放页只有视频显示，其他显示白页面

### ISSUE THREAD

**Issue by MaskPaperMan** [ddgksf2013/ddgksf2013#70]
![IMG_7711](https://github.com/ddgksf2013/ddgksf2013/assets/20158461/06b35648-e46f-4bdf-be7a-6ac3056a38fd)
![IMG_7712](https://github.com/ddgksf2013/ddgksf2013/assets/20158461/51a008cc-d532-4cd5-85cc-7b4b00e72b63)

**Comment by zhangyixi1120** [comment]
我没任何问题

**Comment by MaskPaperMan** [comment]
b站的问题
