### ISSUE TITLE
可以搞个surge版本吗

### ISSUE THREAD

**Issue by alexlee728** [ddgksf2013/ddgksf2013#8]

**Comment by iworkcloud** [comment]
+1

**Comment by kid-oh** [comment]
https://raw.githubusercontent.com/chengkongyiban/Surge/main/modules/QX_to_Surge.sgmodule

**Comment by alexlee728** [comment]
> https://raw.githubusercontent.com/chengkongyiban/Surge/main/modules/QX_to_Surge.sgmodule

如何使用呢？
