### ISSUE TITLE
[BUG]你好,广电卡用了规则之后微信响应很慢

### ISSUE THREAD

**Issue by whatever0406** [ddgksf2013/ddgksf2013#82]
APP名称：微信
发生时间：2024年10月16日
使用的脚本或重写：Cuttlefish.conf
使用的工具：QX
问题描述：设备是iphone15pro,原来是联通卡,加了张广电卡做流量卡之后,使用数据时微信接收消息很慢,经常转圈10+秒才能接收到消息,连接wifi或者关闭圈X后就能正常速度接收了,请问是什么问题呢

**Comment by Takematsu888** [comment]
同样遇到这个问题，也是广电卡

**Comment by flyrayrain** [comment]
我也遇到这个问题，也是广电卡，大家有什么解决方案了没？

**Comment by flyrayrain** [comment]
大家可以试下安装 dns 配置文件，转转会快很多的 ，网址在这：https://github.com/paulmillr/encrypted-dns

**Comment by ddgksf2013** [comment]
试试打开QX兼容性增强开关

**Comment by whatever0406** [comment]
> 试试打开QX兼容性增强开关
是的,现在就是这么用的
