### ISSUE TITLE
[BUG] 微博无法刷新

### ISSUE THREAD

**Issue by Xc1Ym** [ddgksf2013/ddgksf2013#86]
APP名称：微博
发生时间：2024年10月29日
使用的脚本或重写： 广告终结者
使用的工具：QX
问题描述：因为屏蔽dns.weibo.cn域名导致微博无法刷新，无法正常使用，对该域名直连后微博功能正常

**Comment by ddgksf2013** [comment]
录频 tg 私信发给我，@ddgksf2013

便于我确认问题
