### ISSUE TITLE
[BUG] QX 自动选择中“需匹配的节点标签-正则”内容错误

### ISSUE THREAD

**Issue by deeeiznc** [ddgksf2013/ddgksf2013#91]
使用的工具：QX
问题描述：默认的是 `^(.(?!(网易|墨鱼)))*$`，无法正常筛选
正确的应该是 `^(?!.*(?:网易|墨鱼)).*$`
![IMG_5188](https://github.com/user-attachments/assets/a49f05bd-1a12-42a3-a52a-8da6f39381df)

**Comment by ddgksf2013** [comment]
fixed
